
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStoreName }}
  namespace: {{ .Values.global.namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.projectId | quote }}
      # NOTE: Configure Workload Identity on the ESO SA and set projectId to your GCP project id.
{{- end }}
