from typing import List

import sqlglot
from sqlglot import expressions
from sqlglot.dialects.snowflake import Snowflake

from src.data_science.snowflake.cortex.cortex_analyst import ExecutableVerifiedQuery
from src.data_science.snowflake.cortex.cortex_semantic_model import CortexSemanticModel, StoredVerifiedQuery, Table


def executable_verified_query(sql: StoredVerifiedQuery, model: CortexSemanticModel) -> ExecutableVerifiedQuery:
    """
    Add the logical CTEs to the given statement e.g. the `__customer` CTE in the example below.

    Note:
        This is a re-implementation of `expand_all_logical_tables_as_ctes` in `semantic-model-generator`:
        => https://github.com/Snowflake-Labs/semantic-model-generator/blob/release/v0.1.33/semantic_model_generator/data_processing/cte_utils.py#L287-L334

    Example:
        Input:
            ```sql
            select
                nation_key,
                count(customer_key) as customer_count
            from __customer
            group by nation_key
            ```

        Output:
            ```sql
            with
            __customer as (
                select
                    c_custkey as customer_key,
                    c_nationkey as nation_key
                from snowflake.tpch_sf1000.customer
            )
            select
                nation_key,
                count(customer_key) as customer_count
            from __customer
            group by nation_key
            ```
    """
    logical_table_ctes = [logical_table_cte(table) for table in model.tables]
    sql_ast = sqlglot.parse_one(sql, read=Snowflake)

    # Add the logical table CTE to the WITH clause.
    if with_clause := sql_ast.args.get("with"):
        with_clause.set("expressions", [*logical_table_ctes, *with_clause.expressions])
    else:
        sql_ast.set("with", expressions.With(expressions=logical_table_ctes))

    return sql_ast.sql(dialect=Snowflake, pretty=True)


def logical_table_cte(model: Table) -> expressions.CTE:
    cte_name = f"{_LOGICAL_TABLE_PREFIX}{model.name.lower()}"
    cte_columns = ", ".join(
        f"{col.expr} as {col.name}" if col.expr != col.name else col.expr for col in model.columns()
    )

    cte_sql = f"""
        with {cte_name} as (
            select {cte_columns}
            from {model.base_table.table_path()}
        )
    """
    return sqlglot.parse_one(cte_sql, read=Snowflake, into=expressions.With).expressions[0]


def stored_verified_query(sql: ExecutableVerifiedQuery, model: CortexSemanticModel) -> StoredVerifiedQuery:
    """
    Remove the logical CTEs from the given statement e.g. the `__customer` CTE in the example below.

    Note:
        This is a re-implementation of `remove_ltable_cte` in `semantic-model-generator`:
        => https://github.com/Snowflake-Labs/semantic-model-generator/blob/release/v0.1.33/semantic_model_generator/data_processing/cte_utils.py#L78-L100

    Example:
        Input:
            ```sql
            with
            __customer as (
                select
                    c_custkey as customer_key,
                    c_nationkey as nation_key
                from snowflake.tpch_sf1000.customer
            )
            select
                nation_key,
                count(customer_key) as customer_count
            from __customer
            group by nation_key
            ```

        Output:
            ```sql
            select
                nation_key,
                count(customer_key) as customer_count
            from __customer
            group by nation_key
            ```
    """
    sql_ast = sqlglot.parse_one(sql, read=Snowflake)

    logical_tables = [table.name.lower() for table in model.tables]

    with_clause = sql_ast.args.get("with")
    if with_clause is None or not is_logical_table_cte(with_clause.expressions[0].alias, logical_tables):
        raise ValueError("Analyst queries must contain the logical CTE.")

    # Remove logical table CTEs
    non_logical_cte = [cte for cte in with_clause.expressions if not is_logical_table_cte(cte.alias, logical_tables)]
    with_clause.set("expressions", non_logical_cte)

    # Remove the entire WITH clause if it's empty
    if not with_clause.expressions:
        sql_ast.set("with", None)

    return sql_ast.sql(dialect=Snowflake, pretty=True).replace(" /* Generated by Cortex Analyst */", "")


def is_logical_table_cte(cte_name: str, logical_tables: List[str]) -> bool:
    is_prefixed = cte_name.startswith(_LOGICAL_TABLE_PREFIX) and len(cte_name) > len(_LOGICAL_TABLE_PREFIX)
    is_logical_table = cte_name.replace(_LOGICAL_TABLE_PREFIX, "").lower() in logical_tables
    return is_prefixed and is_logical_table


_LOGICAL_TABLE_PREFIX = "__"
